# Generated by Django 5.2.6 on 2025-09-13 15:27

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auth_extensions'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='emailchallenge',
            name='purpose',
            field=models.CharField(choices=[('login_2fa', 'Login 2FA'), ('signup_verify', 'Signup Verify'), ('reset', 'Reset Password')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='emailchallenge',
            index=models.Index(fields=['user', 'purpose', 'created_at'], name='accounts_em_user_id_f8d7e4_idx'),
        ),
        migrations.AddIndex(
            model_name='trusteddevice',
            index=models.Index(fields=['user', 'device_id'], name='accounts_tr_user_id_85616d_idx'),
        ),
        migrations.AlterConstraint(
            model_name='user',
            name='accounts_user_email_lower_uniq',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='accounts_user_email_lower_uniq', violation_error_message='E-mail já cadastrado'),
        ),
    ]
