# Generated by Django 5.2.6 on 2025-09-24 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options_alter_emailchallenge_purpose_and_more'),
        ('accounts', '0003_user_demographics'),
    ]

    operations = [
    ]
