version: "3.9"

services:
  db:
    image: postgres:16
    container_name: app-postgres
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app}
      # Garante cluster em UTF-8 com locale que aceita emoji
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=C.UTF-8 --lc-ctype=C.UTF-8"
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h 0.0.0.0"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      # Volume local dentro do repositório
      - ./.data/postgres:/var/lib/postgresql/data
      # Scripts de inicialização opcionais (.sql/.sh)
      - ./docker/postgres/init:/docker-entrypoint-initdb.d:ro

  redis:
    image: redis:7-alpine
    container_name: app-redis
    restart: unless-stopped
    ports: ["6379:6379"]
    command: ["redis-server","--save","","--appendonly","no"]