# Generated by Django 5.2.6 on 2025-09-10 18:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('metering', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_cents', models.PositiveIntegerField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.invoice')),
                ('metering_event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_line', to='metering.meteringevent')),
            ],
            options={
                'indexes': [models.Index(fields=['invoice'], name='billing_inv_invoice_6c1311_idx')],
            },
        ),
    ]
