# Generated by Codex CLI: add billing cycle fields and invoice idempotency
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_invoiceline"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprofile",
            name="timezone",
            field=models.CharField(default="America/Sao_Paulo", max_length=64),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="billing_anchor_day",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="anchor_set_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="last_billed_period_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="payment_method_status",
            field=models.CharField(choices=[("none", "None"), ("active", "Active"), ("expired", "Expired")], default="none", max_length=12),
        ),
        migrations.AddField(
            model_name="invoice",
            name="idempotency_key",
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]

