# Generated by Django 5.2.6 on 2025-09-10 18:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('resource_type', models.CharField(choices=[('card', 'Card'), ('link', 'Link'), ('gallery', 'Gallery'), ('appointment', 'Appointment')], max_length=20)),
                ('event_type', models.CharField(choices=[('publish', 'Publish'), ('link_add', 'Link Added'), ('gallery_add', 'Gallery Added'), ('appointment_confirmed', 'Appointment Confirmed')], max_length=40)),
                ('unit_price_cents', models.PositiveIntegerField()),
                ('cadence', models.CharField(choices=[('once', 'Once'), ('monthly', 'Monthly'), ('per_event', 'Per Event')], default='per_event', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['resource_type', 'event_type', 'is_active'], name='metering_pr_resourc_6060f5_idx')],
            },
        ),
        migrations.CreateModel(
            name='MeteringEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource_type', models.CharField(choices=[('card', 'Card'), ('link', 'Link'), ('gallery', 'Gallery'), ('appointment', 'Appointment')], max_length=20)),
                ('event_type', models.CharField(choices=[('publish', 'Publish'), ('link_add', 'Link Added'), ('gallery_add', 'Gallery Added'), ('appointment_confirmed', 'Appointment Confirmed')], max_length=40)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price_cents', models.PositiveIntegerField(default=0)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduling.appointment')),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cards.card')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduling.schedulingservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'occurred_at'], name='metering_me_user_id_fa54c4_idx'), models.Index(fields=['resource_type', 'event_type'], name='metering_me_resourc_24fb9c_idx')],
            },
        ),
    ]
