# Generated by Django 5.2.6 on 2025-09-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/cards/avatars/'),
        ),
    ]
