# Generated by Django 5.2.6 on 2025-09-10 20:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_card_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardaddress',
            old_name='city',
            new_name='bairro',
        ),
        migrations.RenameField(
            model_name='cardaddress',
            old_name='state',
            new_name='cidade',
        ),
        migrations.RenameField(
            model_name='cardaddress',
            old_name='street',
            new_name='logradouro',
        ),
        migrations.RenameField(
            model_name='cardaddress',
            old_name='zip',
            new_name='numero',
        ),
        migrations.RenameField(
            model_name='cardaddress',
            old_name='country',
            new_name='uf',
        ),
        migrations.AddField(
            model_name='cardaddress',
            name='cep',
            field=models.CharField(default='00000-000', help_text='CEP no formato 00000-000', max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardaddress',
            name='complemento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cardaddress',
            name='pais',
            field=models.CharField(default='BR', max_length=2),
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('whatsapp', 'WhatsApp'), ('x', 'X'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('github', 'GitHub'), ('site', 'Site')], max_length=20)),
                ('label', models.CharField(blank=True, max_length=80)),
                ('url', models.URLField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='cards.card')),
            ],
            options={
                'indexes': [models.Index(fields=['card', 'order'], name='cards_socia_card_id_726e00_idx')],
            },
        ),
    ]
