# Generated by Django 5.2.6 on 2025-09-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_rename_city_cardaddress_bairro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='avatar_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='avatar_rev',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='avatar_w128',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/cards/avatars/'),
        ),
        migrations.AddField(
            model_name='card',
            name='avatar_w64',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/cards/avatars/'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='thumb_w256',
            field=models.FileField(blank=True, null=True, upload_to='cards/gallery/'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='thumb_w768',
            field=models.FileField(blank=True, null=True, upload_to='cards/gallery/'),
        ),
    ]
