# Generated by Django 5.2.6 on 2025-09-10 21:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_card_avatar_hash_card_avatar_rev_card_avatar_w128_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='nickname',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AddConstraint(
            model_name='card',
            constraint=models.UniqueConstraint(condition=models.Q(('nickname', None), _negated=True), fields=('nickname',), name='uniq_card_nickname'),
        ),
    ]
