# Generated by Django 5.2.6 on 2025-09-10 23:22

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_card_nickname_card_uniq_card_nickname'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='card',
            name='uniq_card_nickname',
        ),
        migrations.AddConstraint(
            model_name='card',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nickname'), condition=models.Q(('nickname', None), _negated=True), name='uniq_card_nickname_lower'),
        ),
    ]
