# Generated by Django on 2025-10-01
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0010_card_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="notification_phone",
            field=models.CharField(max_length=20, blank=True, null=True),
        ),
    ]

