# Generated by Django 5.2.6 on 2025-10-18 19:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_card_notification_phone'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='importance',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_items', to='scheduling.schedulingservice'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='visible_in_gallery',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='galleryitem',
            index=models.Index(fields=['card', 'service'], name='cards_galle_card_id_f33a58_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryitem',
            index=models.Index(fields=['service', 'importance'], name='cards_galle_service_1f6472_idx'),
        ),
    ]
