# Generated by Django 5.2.6 on 2025-10-31 19:12

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_resched_requested_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('price_delta_cents', models.IntegerField(default=0)),
                ('extra_duration_minutes', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'ordering': ('order', 'name'),
            },
        ),
        migrations.RenameIndex(
            model_name='reschedulerequest',
            new_name='scheduling__appoint_ec6c64_idx',
            old_name='scheduling_reschedule_idx',
        ),
        migrations.AddField(
            model_name='appointment',
            name='base_price_cents',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='appointment',
            name='options_snapshot_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='appointment',
            name='price_cents',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='schedulingservice',
            name='price_cents',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='serviceoption',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='scheduling.schedulingservice'),
        ),
        migrations.AddIndex(
            model_name='serviceoption',
            index=models.Index(fields=['service', 'order'], name='scheduling__service_f177c9_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceoption',
            index=models.Index(fields=['service', 'is_active'], name='scheduling__service_baf89e_idx'),
        ),
    ]
