# Generated by Django 5.2.6 on 2025-09-14 21:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email')], max_length=10)),
                ('to', models.CharField(max_length=200)),
                ('template_code', models.CharField(max_length=80)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('bounced', 'Bounced'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=20)),
                ('provider', models.CharField(blank=True, choices=[('twilio', 'Twilio'), ('sendgrid', 'SendGrid'), ('dev', 'Dev Mode')], max_length=20, null=True)),
                ('provider_message_id', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('error_code', models.CharField(blank=True, max_length=50, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('idempotency_key', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('is_dlq', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='notificatio_status_9a4505_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.CharField(max_length=20)),
                ('provider_response_json', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts_log', to='notifications.notification')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email')], max_length=10)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('body_txt', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('code', 'channel'), name='uniq_template_code_channel')],
            },
        ),
    ]
